### PR TITLE
[#225] issue fixed and added tests

### PR DESCRIPTION
**Pull request by Evengining**
#225 fixes

### CODE REVIEW

**Comment by neongreen** [comment]
(Still formulating the question.)

**Comment by neongreen** [comment]
```
      case literal @ Literal(_)    => literal
      case space @ Space(_)        => space
      case escaped @ Escaped("\\") => Escaped("\\" + escaped.repr)
      case token: Token            => Escaped(token.repr)
```

This code seems wrong to me. Explicitly checking for things like `"\\"` is rarely the right approach.

The semantics of `Escaped` is "whatever is inside was prefixed with a '\' in the regex". E.g. `\a` corresponds to `Escaped("a")`.

Note that it can contain any special characters, e.g. `Escaped("x{1234}")` is a perfectly valid thing that we might want to have in the future. Right now we parse `\x{1234}` as `Escaped("x"), ...`, but it's a bug. Just prepending "\" to an `Escaped` is not enough to escape it.

What we should actually do is to throw away the `match` completely and just escape the following characters in the incoming string: `[]{}()^$\|*+?.`

**Comment by neongreen** [comment]
Another test case to add: `[[:alpha:]]` should become something like `\[\[:alpha:\]\]`.

**Comment by kamilongus** [comment]
@Evengining Please write more detailed commit messages next time

**Pull request merged**
