### PR TITLE
Added new ip and domain

### PR DESCRIPTION
**Pull request by Kabowyad**

### CODE REVIEW

**Comment by kamilongus** [comment]
@Kabowyad you want to have a list of allowed hosts as arguments?

**Comment by kamilongus** [comment]
@Kabowyad may be we can use HOCON-syntax with list allowed hosts from environment? Let's check it.

**Comment by Kabowyad** [comment]
@kamilongus Немного не взлетело
`Cannot concatenate object or list with a non-object-or-list, Quoted("[188.166.85.208,cloud.digitalocean.com,s1.codesearch.aelve.com]") and SimpleConfigList(["localhost"]) are not compatible`

**Comment by Kabowyad** [comment]
Можно сделать так
`play.filters.hosts {
  allowed = []
  allowed.0 = ${?ALLOWED_HOSTS_1}
  allowed.1 = ${?ALLOWED_HOSTS_2}
}`
И потом при запуске контейнера
`-e ALLOWED_HOSTS_1="a"
-e ALLOWED_HOSTS_2="b"`

**Comment by neongreen** [comment]
Russian -> Slack

**Comment by kamilongus** [comment]
@Kabowyad There is such an option without changing the configuration file: 
```
-Dplay.filters.hosts.allowed.1=188.166.85.208
-Dplay.filters.hosts.allowed.2=cloud.digitalocean.com
-Dplay.filters.hosts.allowed.3=s1.codesearch.aelve.com
```
Perhaps you suggested this option before.

**Comment by Som3** [comment]
solution by @kamilongus work, we can change docker file and pass env variables into `java -Dplay.filters.hosts.allowed.1=188.166.85.208 -jar ...`

**Pull request merged**
